# Generated by Django 5.1 on 2024-08-26 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=200, unique=True, verbose_name='شماره موبایل')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='ایمیل')),
                ('phone_activate_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد فعال سازی موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='موبایل فعال / غیر فعال')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='موبایل فعال / غیر فعال')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='آواتار')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('salt', models.CharField(max_length=50, unique=True, verbose_name='salt')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیرکل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 't_users',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='دلیل بلاک')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر بلاک شده')),
            ],
            options={
                'verbose_name': 'کاربر بلاک شده',
                'verbose_name_plural': 'کاربران بلاک شده',
                'db_table': 't_blocked_users',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['register_date'], name='t_users_registe_21dc19_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='t_users_phone_f8829c_idx'),
        ),
    ]
