# Generated by Django 5.1 on 2024-08-28 11:05

import apps.course.models.course
import apps.course.models.course_session
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان گروه')),
                ('slug', models.SlugField(max_length=255, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'گروه دوره',
                'verbose_name_plural': 'گروه دوره ها',
                'db_table': 't_course_categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام دوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover', models.ImageField(max_length=255, upload_to=apps.course.models.course.upload_course_image, verbose_name='تصویر دوره')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('slug', models.SlugField(max_length=255, verbose_name='عنوان در url')),
                ('is_complete', models.BooleanField(verbose_name='تمام شده/ درحال برگزاری')),
                ('support', models.CharField(max_length=255, verbose_name='پشتیبانی دوره')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اد کننده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.coursecategory', verbose_name='گروه دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'db_table': 't_courses',
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان جلسه')),
                ('time', models.DurationField(verbose_name='زمان')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان بودن')),
                ('video', models.FileField(upload_to=apps.course.models.course_session.upload_session_file, verbose_name='فایل جلسه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسه ها',
                'db_table': 't_sessions',
            },
        ),
    ]
