# Generated by Django 5.1 on 2024-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_slug_alter_coursecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیر فعال'),
        ),
    ]
