# Generated by Django 5.1 on 2024-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursecategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='support',
            field=models.CharField(max_length=255, null=True, verbose_name='پشتیبانی دوره'),
        ),
    ]
