# Generated by Django 5.1 on 2024-08-29 16:42

import apps.article.models.article
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان گروه')),
                ('slug', models.SlugField(max_length=255, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقاله ها',
                'db_table': 't_article_categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='نام مقاله')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('body', models.TextField(verbose_name='متن مقاله')),
                ('cover', models.ImageField(max_length=255, upload_to=apps.article.models.article.upload_article_image, verbose_name='تصویر مفاله')),
                ('slug', models.SlugField(max_length=255, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.articlecategory', verbose_name='گروه مفاله')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اد کننده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
                'db_table': 't_articles',
            },
        ),
    ]
